<a href="https://colab.research.google.com/github/ParkerC12345/ds2002-fa26/blob/main/notebooks/01-foundations/2026-09-04%20%E2%80%94%20Submission%20Drill%20and%20Fix%20a%20Broken%20Notebook%20%E2%80%94%20Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DS2002 · Submission Drill and Fix a Broken Notebook

**Lab — 2026-09-04 · Fall 2026**  

---

## Lab 02 — Submission Drill and Fix a Broken Notebook

You have inherited a notebook that does not run. This is the most common way you will meet other people's code, so it is worth practicing deliberately.

Seven cells below are broken. Five throw an error, and two return a wrong answer without complaining at all — those are the dangerous ones. Fix all seven, prove your fixes with assertions, then push through the full submit loop.

**Submit in Canvas:** repository link and notebook link.

### How to read an error before you fix it

Python's traceback is read **bottom up**. The last line names the exception and the problem; the line above it points at your code.

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    print(greeting)
NameError: name 'greeting' is not defined
```

Four exceptions cover most of what you will hit this semester:

| Exception | Usually means |
|---|---|
| `NameError` | The variable was never created, or the cell that created it never ran |
| `TypeError` | You mixed types — text where a number belongs is the classic |
| `KeyError` | That column or dictionary key does not exist. Check spelling and case |
| `FileNotFoundError` | The path is wrong for *this* environment |

For each fix below, write one sentence in the markdown cell saying what was actually wrong. "It works now" is not a diagnosis.

### Bug 1 — a name that does not exist

In [1]:
# TODO: fix so this prints a greeting
greeting = 'Hello, have a great day.'
print(greeting)

Hello, have a great day.

Intially, there was not a variable named greeting and the greeting message was not a string that python could recongize as text.

**What was wrong:** _..._

### Bug 2 — text where a number belongs

This should print `30`. Note that `'10' + 20` and `'10' + '20'` fail in different ways — make sure you know which one you are looking at.

In [2]:
# TODO: fix so total is the number 30
total = 10 + 20
print(total)

30

The string that the numbers were in was preventing python from being able to recongize the numeric values

**What was wrong:** _..._

### Bug 3 — off the end of a list

In [3]:
items = ['burger', 'poncho', 'hat']

# TODO: print the LAST item, and do it in a way that still works
#       if someone adds a fourth item tomorrow
print(items[-1])

hat

I used the index [-1] so that the last item will always print, no matter the number of items, the [3] would print the 3rd value no matte rhow manny there are.

**What was wrong:** _..._

### Bug 4 — no error, wrong answer

This is supposed to be the average. It prints a number, and the number is wrong.

In [4]:
nums = [2, 4, 6, 8]
average = sum(nums) / len(nums)
print('average:', average)

average: 5.0

The original equation was simply dividing the sum by 2 and did not take the average. Using len(nums) will ensure the sum is always divided by the total amount of numbers.

**What was wrong:** _..._

### Bug 5 — a table that cannot exist

In [5]:
import pandas as pd

df = pd.DataFrame({'item': ['a', 'b'], 'price': [1, 2]})
df

  item  price
0    a      1
1    b      2

The DF did not have an item for price 3 causing the DF to have a fualty structure. I removed price 3 so that there are no missing values, which allows the table to exist.

**What was wrong:** _..._

### Bug 6 — the answer changes when you re-run it

Run the next cell three times and watch the total move. Then fix it using what you built Wednesday: leave the source data alone and derive a new column from it. Your fix must give the same total on every run.

In [6]:
sales = pd.DataFrame({
    'game': ['NC State', 'Louisville'],
    'units': [1450, 1610],
})

# TODO: rewrite these two lines so re-running cannot change the answer
sales['units with fee'] = sales['units'] * 1.05
print('total units:', round(sales['units with fee'].sum(), 2))

total units: 3213.0

The 'units' column was being over written by each calculation, so I created a new colum for the units with fee (1.05) taken into account when caculating the unit price.

In [7]:
# Proof — this must print the same number three times
for _ in range(3):
  sales['units with fee'] = sales['units'] * 1.05
  print('triple test total units: ', round(sales['units with fee'].sum(), 2))

    # TODO: rebuild from the raw values and print your total
rebuild = pd.DataFrame({
    'game': ['NC State', 'Louisville'],
    'units': [1450, 1610],
})

rebuild['units with fee'] = sales['units'] * 1.05
print('rebuild total units: ', round(sales['units with fee'].sum(), 2))

triple test total units:  3213.0
triple test total units:  3213.0
triple test total units:  3213.0
rebuild total units:  3213.0

I finished the 'for' loop to triple test the total units. I then rebuilt the Dataframe from the raw values and confirmed it ran correctly by calculating its total untis.

**What was wrong:** _..._

### Bug 7 — a path from someone else's laptop

This notebook was written on a machine you do not have. Fix it with the pattern from Wednesday's studio: look for the file, and fall back to the inline sample so the notebook still runs for whoever opens it next.

In [8]:
import os
from io import StringIO

SAMPLE = '''game,units\nNC State,1450\nLouisville,1610\n'''

# TODO: replace this with a lookup + fallback that works anywhere

path = 'gameday_orders.csv'
if os.path.isfile(path):
  orders = pd.read_csv(path)
else:
  orders = pd.read_csv(StringIO(SAMPLE))

orders

         game  units
0    NC State   1450
1  Louisville   1610

This two step 'if else' pathway allows anyone to run the code even if they do not have the .csv file. The Else path allows someone to open the DF based off of the sample. The original code just had the pathway to a Desktop preventing anyone on a different computer from running the code.

**What was wrong:** _..._

### Part 8 — prove the fixes

Assertions are how you state what must be true. If one fails, the notebook stops and tells you which claim broke — much better than scrolling for a wrong number.

**TODO:** uncomment each line and make them all pass.

In [9]:
assert isinstance(greeting, str) and greeting != ''
assert total == 30
assert items[-1] == 'hat'
assert average == 5
assert len(df) == 2
assert len(orders) >= 2
print('All checks passed.')

All checks passed.

I had to add a varibale named 'greeting' for Part 1 and correct the Table for part 5 to two variables.

### Part 9 — the submit drill

This is the part that is actually being graded on process. Do it in order.

1. **Restart the kernel and Run All.** Zero errors, top to bottom.
2. Download the notebook and put it in your repo under `notebooks/01-foundations/`, named `2026-09-04 — Submission Drill and Fix a Broken Notebook — Lab.ipynb`.
3. Commit with a message that says what you did, then push.
4. Confirm on github.com that the file is there and opens.
5. Fill in the cell below and submit both links in Canvas.

**TODO:** fill in the four values and make the check pass.

In [10]:
import re

repo_url = 'https://github.com/ParkerC12345/ds2002-fa26'
commit_sha = '1c9aad9'
notebook_link = 'https://colab.research.google.com/github/ParkerC12345/ds2002-fa26/blob/main/notebooks/01-foundations/2026-09-04%20%E2%80%94%20Submission%20Drill%20and%20Fix%20a%20Broken%20Notebook%20%E2%80%94%20Lab.ipynb'
ran_restart_and_run_all = True   # TODO: set True after you actually do it

checks = {
    'repo URL is a github.com URL':
        repo_url.startswith('https://github.com/ParkerC12345/ds2002-fa26')
        and repo_url.count('/') >= 4,
    'commit hash looks like a hash':
        bool(re.fullmatch(r'[0-9a-f]{7,40}', commit_sha.strip())),
    'notebook link filled in':
        notebook_link.startswith('http'),
    'restarted and ran all':
        ran_restart_and_run_all is True,
}

for label, passed in checks.items():
    print('PASS' if passed else 'FAIL', '-', label)

print()
print('Ready to submit:', all(checks.values()))

PASS - repo URL is a github.com URL
PASS - commit hash looks like a hash
PASS - notebook link filled in
PASS - restarted and ran all

Ready to submit: True

I completed all 5 steps and filled in the 'TODO' sections of the cell.

### Write-up

Bugs 4 and 6 did not raise an error. In a few sentences: how would you catch that class of bug in a project where you do not already know the right answer? Name something concrete you could add to a notebook.

The primary issue with both Bug 4 and Bug 6 is that the original code only provided the correct output in one circumstance. The code in Bug 4 would only be correct when there are two numbers in the set, and the code in Bug 6 would only be correct the first time it is ran before 'units over-writes itself. For bugs like these, I would use invarient functions that correctly operate no matter how the dataset changes. For Bug 4, I learned to use 'lens(nums)' instead of dividing by a specfic number so that the sum is always divided by the total amount of numbers. For bug 6, I learned to use a for loop to catch the code being overriden as it ran multiple times. These invarient operations provide failbreaks in case I make a computational mistake.

### Stretch

Write a `check_orders(df)` function that raises a clear error if the frame is missing either expected column, has zero rows, or contains a negative value in `units`. Then call it on `orders`. This is the shape of validation you will want in both projects.

In [11]:
# stretch

def check_orders(df):
  if 'game'not in df.columns or 'units' not in df.columns:
    raise ValueError('DataFrame must have columns named "game" and "units"')

  if len(df) == 0:
    raise ValueError('Dataframe must have rows')

  if (df['units'] < 0).any():
    raise ValueError('Dataframe must not contain negative values')

check_orders(orders)

Following the 'if' statements we have been working on this week, I create three 'if' statements texting if the DF is missing expected columns, has zero rows, or has negative values. There are no ValueErrors raised. The 'orders' DF therefore passed all three of the tests raised.